name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: node:14.5-buster
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can
          # generate changelogs with the correct commits.
          fetch-depth: 0
      - name: Install
        run: npm i -g pnpm && pnpm i
      - name: Changesets
        id: changesets
        uses: ianwalter/action@debug
        with:
          publish: pnpx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
